server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI4G2rFKsVU4e3vF2uMjdo
    keysecret: CRYsB0l84OsWr6SvqLGfJMRvQUuAgE
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: bb-file-biaob